config/routes.rb
Rails.application.routes.draw do


  # ------ Recipes routes ------
  resources :recipes
  # ----------------------------

  # ------ Users routes ------
  resources :users
  # --------------------------

  get '/' => 'recipes#index', :as => :root

  # ------ Authentication routes ------
  # /session/new       login form
  get '/login'     => 'session#new'
  # /session           logout
  delete '/logout' => 'session#destroy'
  # /session           after submit form for login
  post '/login'    => 'session#create'
  # ----------------------------------


  # ------ API routes ------
  # /api/seed                 retrieve data from weeatt api
  get '/api/seed'         => 'api#seed'
  # /api/add                  adds recipes to DB
  post '/api/add'         => 'api#addRecipe'
  # /api/list                 provide json search results
  get '/api/recipes/list' => 'api#list'
  # /api/recipe/:id           provide json recipe details
  get '/api/recipes/:id'  => 'api#show'
  # ------------------------


end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :user
	belongs_to :recipe
	
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base

	belongs_to :user
	belongs_to :recipe
	
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

	has_many :favourites
	has_many :users, :through => :favourites

	has_many :comments
	has_many :users, :through => :comments

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	has_many :favourites
	has_many :recipes, :through => :favourites

	has_many :comments
	has_many :recipes, :through => :comments

  # Email validation
  validates :email, :presence => true, :uniqueness => true
  validates_format_of :email, :with => /@/

  # Password validation
  validates :password, confirmation: true
  validates_length_of :password, :in => 6..20, :on => :create
  
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  # retrieve data from weeatt API and post to our DB at addRecipe
  def seed  
  end

  # action data posting to DB
  def addRecipe

    params['results'].each do |result|
      recipe = Recipe.new
      recipe.title = result[1]['name']
      if result[1]['images'] &&
        result[1]['images'].values.first["large_image_path"] != '/photos/large/missing.png'
        # deal with ridiculous image nesting
        recipe.image_url = result[1]['images'].values.first["large_image_path"]
      else
        recipe.image_url = nil # for recipes with no images
      end
      recipe.description = result[1]['description']
      recipe.method = result[1]['instructions']
      recipe.ingredients = result[1]['ingredients']
      recipe.cook_time = 15 + rand(26)
      recipe.nbr_times_cooked = 5 + rand(146)
      recipe.user_rating = 1 + rand(5)
      if recipe.image_url
        recipe.save
      else
        next
      end
    end

    redirect_to root_path # lol this don't work no good

  end

  # supply json search results from DB
  def list
    
    recipes = Recipe.all
    render :json => recipes.to_json

  end

  # supply json recipe detail from DB
  def show

    recipe = Recipe.find(params[:id])
    render :json => recipe.to_json

  end


end

# add if r.save alternatives
# add check for duplicates;
# consider method for cook_time
# consider method for nbr_times_cooked
# consider method for user rating

# filter for relevant recipes at some point

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  # ------------- Authentication ------------- 
  def logged_in?
    !!current_user
  end
  helper_method :logged_in? #allows the helper method to be used in views

  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user
  # ------------------------------------------ 


end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  #login form
  def new
    if logged_in?
      redirect_to root_path      
    end
  end

  #logging in
  def create
    @user = User.find_by(email: params[:session][:email])

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      render :json => { msg: [0,"You've successfully logged in."]}
    else
      render :json => { msg: [1,"Your email and/or password were invalid. Please try again."]}
    end
  end

  # logging out 
  def destroy
    session[:user_id] = nil
    render :json => {}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  
  def new
    @user = User.new 
  end

  def create
    @user = User.new
    # @user.email = params[:user][:email]
    # @user.password = params[:user][:password]
    @user.email = params[:email]
    @user.password = params[:password]
    password_cont = params[:password_confirmation]
    
    if @user.save
      flash[:notice] = "You signed up successfully"
      flash[:color]= "valid"
      redirect_to root_path

    # Re-render new if User.save is unsuccessful
    else 
      flash[:notice] = "Form is invalid"
      flash[:color]= "invalid"

      @errors = @user.errors.full_messages
      render :new
    end
  end

  # Strong params
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PastaMasta - Simple pasta dishes</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" type="image/ico" href="favicon.ico" />
  <link href='//fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Titillium+Web:400,400italic,600italic,600,700,700italic,900,300italic,300,200italic,200' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,900,700,500,300,100' rel='stylesheet' type='text/css'>
</head>
<body>

<!-- HEADER -->
  <header>
    <div class="header-logo">
      <!-- <h1>PASTA MASTA</h1> -->
      <%= image_tag("icons/logo.png", 'class'=> "img-logo") %>

    </div>

    <div class="header-content">
      <div class="header-searchlogo">
        <div class="search-dropdown"><%= icon('fa fa-search fa-2x', class: "search-icon") %></div>
      </div>

      <div class="header-accountlogo">
        <div class="modal">
          <label for="modal-1">
            <div id="user-icon" class="modal-trigger">
              <% if logged_in? %>
                <%= icon('fa fa-sign-out fa-2x') %>
              <% else %>
                <%= icon('fa fa-user fa-2x') %>
              <% end %>
            </div>
          </label>
          <input class="modal-state" id="modal-1" type="checkbox" />
          <div class="modal-fade-screen">
            <div class="modal-inner">
              <div class="modal-close" for="modal-1"></div>

              <!-- SIGN-UP / LOGIN FORMS -->
              <div class="form-wrap">
                <div class="tabs">
                  <h3 class="login-tab"><a class="active" href="#login-tab-content">Login</a></h3>
                  <h3 class="signup-tab"><a href="#signup-tab-content">Sign Up</a></h3>
                </div><!--.tabs-->

                <div class="tabs-content">
                  <div id="login-tab-content" class="active">
                    <%= form_for :session, remote: true, url: login_path, html: { id: 'login-form'} do |f| %>
                      <p><%= f.email_field :email, class: 'input', placeholder: "Email" %></p>
                      <p><%= f.password_field :password, class: 'input', placeholder: "Password" %></p>
                      
                      <%= f.submit "Login", class: "button" %>
                    <% end %><!--.login-form-->

                    <div class="invalid-login">
                      <p>Your email and/or password were invalid. Please try again.</p>
                    </div><!--.invalid-login-->

                    <div class="help-text">
                      <p><a href="#">Forgot your password?</a></p>
                    </div><!--.help-text-->
                  </div><!--.login-tab-content-->

                  <div id="signup-tab-content">
                    <%= form_tag users_path do %>
                      <p><%= text_field_tag :email, nil, class: 'input', placeholder: "Email" %></p>
                      <p><%= text_field_tag :password, nil, class: 'input', placeholder: "Password", type: 'password' %></p>
                      <p><%= text_field_tag :password_confirmation, nil, class: 'input', placeholder: "Confirm password", type: 'password' %></p>
                      
                      <p><%= submit_tag 'Sign Up', class: 'button' %></p>
                    <% end %><!--.signup-form-->

                    <div class="help-text">
                      <p>By signing up, you agree to our</p>
                      <p><a href="#">Terms of service</a></p>
                    </div><!--.help-text-->
                  </div><!--.signup-tab-content-->
                </div><!--.tabs-content-->
              </div><!--.form-wrap-->
              <!-- END SIGN-UP / LOGIN FORMS -->

            </div><!--.modal-inner-->
          </div><!--.modal-fade-screen-->
        </div><!--.modal-->


      </div><!--.header-accountlogo-->
    </div><!--.header-content-->
  </header>


<div class="header-spacer"></div>


  <div class="search-wrapper">

      <%= image_tag("icons/beef.svg", 'data'=> {'filter'=> "beef"}, 'class'=> "search-img", 'alt'=> "beef") %>
      <%= image_tag("icons/pork.svg", 'data'=> {'filter'=> "pork"}, 'class'=> "search-img", 'alt'=> "pork") %>
      <%= image_tag("icons/poultry.svg", 'data'=> {'filter'=> "poultry"}, 'class'=> "search-img", 'alt'=> "poultry") %>
      <%= image_tag("icons/lamb.svg", 'data'=> {'filter'=> "lamb"}, 'class'=> "search-img", 'alt'=> "lamb") %>
      <%= image_tag("icons/seafood.svg", 'data'=> {'filter'=> "seafood"}, 'class'=> "search-img", 'alt'=> "seafood") %>
      <%= image_tag("icons/tomato.svg", 'data'=> {'filter'=> "tomato"}, 'class'=> "search-img", 'alt'=> "tomato") %>
      <%= image_tag("icons/green.svg", 'data'=> {'filter'=> "green"}, 'class'=> "search-img", 'alt'=> "green") %>
      <%= image_tag("icons/mushroom.svg", 'data'=> {'filter'=> "mushroom"}, 'class'=> "search-img", 'alt'=> "mushroom") %>
      <%= image_tag("icons/eggplant.svg", 'data'=> {'filter'=> "eggplant"}, 'class'=> "search-img", 'alt'=> "eggplant") %>
      <%= image_tag("icons/cream.svg", 'data'=> {'filter'=> "cream"}, 'class'=> "search-img", 'alt'=> "cream") %>
      <%= image_tag("icons/salad.svg", 'data'=> {'filter'=> "salad"}, 'class'=> "search-img", 'alt'=> "salad") %>
      <%= image_tag("icons/bake.svg", 'data'=> {'filter'=> "bake"}, 'class'=> "search-img", 'alt'=> "bake") %>

      <button class="search-execute search-img">Go!</button>
  </div>

  
<%= yield %>

<!-- FOOTER -->
<footer class="footer-2" role="contentinfo">
<div class="footer-links wrapper">

    <div class="footer-primary-links">
      <ul>
        <li>
          <div class="modal">
            <label for="modal-2">
              <div id="about-modal-text" class="modal-trigger">
                About
              </div>
            </label>
            <input class="modal-state" id="modal-2" type="checkbox" />
            <div class="modal-fade-screen">
              <div class="modal-inner">
                <div class="modal-close" for="modal-2">
                  
              </div>
      
                <article class="type-system-sans">
                  <h1>About Pasta Masta</h1>
                  <h2>"Life is not worth living if I cannot have pasta or bread again." - Monica Seles</h2>
                  <p class="date">6 May 2015</p>
                  <p>Pasta Masta is an app that aims to enable those less confident cooks to become masters of quick and tasty pasta dishes.</p>
                  <p>The recipes are hand picked for beginning cooks, with minimal ingredients, clear easy-to-follow steps and the option to comment and rate recipes used from the site to help others achieve mastery.</p>
                  <p>Included within the recipes are tips to help assist the budding apprentices to become better each time they cook a recipe. Budding cooks don’t have to join the site, but if they choose to sign up, they will be given the chance to tailor the options for dishes shown during search requests.</p>
                  <p>Suggestions and feedback are most welcome. pastamasta@pastamasta.com</p>
                  <p class="author">The Pasta Masta Masters</p>
                </article>
              </div>
            </div>
          </div>
        </li>
      
      
        <li><a href="javascript:void(0)">Contact</a></li>
        <li><a href="javascript:void(0)">Products</a></li>
      </ul>
    </div>

    <div class="footer-secondary-links">
      <ul>
        <li><a href="javascript:void(0)">Terms and Conditions</a></li>
        <li><a href="javascript:void(0)">Privacy Policy</a></li>
      </ul>
    </div>

    </div>

      <div class="social-wrapper">
        <ul class="footer-social">
          <li><a href="javascript:void(0)">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/facebook-logo-circle.png" alt="Facebook">
            </a></li>
          <li><a href="javascript:void(0)">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/twitter-logo-circle.png" alt="Twitter">
          </a></li>
          <li><a href="javascript:void(0)">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/youtube-logo-circle.png" alt="YouTube">
          </a></li>
        </ul>
      </div>

</footer>

<!-- END FOOTER -->

<script>
  $('#login-form').on('ajax:success', function(event, data) {
    if (data.msg[0] === 0) {
      // Successful login

      // Hide the error message within the modal
      $('.invalid-login').hide();

      // Close the modal
      $(".modal-state:checked").prop("checked", false).change();

      // Replace user icon with logout icon
      $('#user-icon > i').removeClass('fa-user').addClass('fa-sign-out');
    } else {
      // Display the error message within the modal
      $('.invalid-login').show();
    }
  });
</script>


</body>
</html>

app/views/recipes/index.html.erb
<div id="recipe-detail">
  
</div>

<div class="cards">
  
</div>

<script>
  applyFilters.getShowRecipes();
</script>

app/views/session/_form.html.erb
<%= form_tag do%>
  
  <%= label_tag :email%>
  <%= text_field_tag :email %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag %>
<% end %>

app/views/session/new.html.erb
<div class="Sign_Form">

<h1>Log in</h1>

<%= render 'form' %>

</div>

app/views/users/_form.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for(@user) do |f| %>
    <p> Email:</br> <%= f.text_field :email%> </p>
    <p> Password:</br> <%= f.password_field :password%></p>
    <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
    <%= f.submit :Signup%>
  <% end %>

  <!-- Validation -->
  <% if !@errors.nil? %>
    <ul class="Signup_Errors">
    <% for message_error in @errors %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>

</div>

app/views/users/all.html.erb
<h2>All Users</h2>

<%= link_to 'new user', new_user_path %>

<% @users.each do |user| %>

  <p>
    <%= link_to user.email, user %> <br> 
    <%= link_to 'edit', edit_user_path(user) %>

    <%= form_for user, method: :delete do |f| %>
      <%= f.submit 'Delete' %>
    <% end %>

  </p>

<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1>A SINGLE USER</h1>

<p>
  <%= @user.email %> <br>
  <%= @user.password_digest %>
</p>